### ISSUE TITLE
No env.sh or settings in developement on localhost

### ISSUE THREAD

**Issue by vladblindu** [iron-meteor/iron-cli#116]
All is perfect except the variables in both env.sh and settings.json that are not accessible.
I started a clean project on a mac. 
What could possibly happen?

**Comment by Francescu** [comment]
Are you running using `meteor` or `iron run` ?

**Comment by vladblindu** [comment]
I signed into eventide mind’s classes and followed all the steps in building a multipage app class.
So it’s definitely iron.

I don’t have a clue where to start my debugging concerning this issue.

Thanks a lot.

Vlad Blindu
vlad.blindu@gmail.com

**Comment by cmather** [comment]
@vladblindu, Can you take two screenshots: (1) the folder layout of your project; and (2) the command you're using to start the server. That would help figure out what might be happening.

**Comment by vladblindu** [comment]
the command is simply “iron” which outputs:
	meteor run --settings /Users/Vlad/Documents/dev-bay/studman-iron/config/development/settings.json
which looks ok to me.

Here’s a snapshot of the dir-tree:


Thanks again for your time

Vlad Blindu
vlad.blindu@gmail.com

**Comment by chrisbutler** [comment]
@vladblindu try changing `export` to `exports` in your env.sh file

**Comment by vladblindu** [comment]
Thanks a lot for your time,

This definitely was an issue. I didn’t realise I had a typo.
I restarted the server, but it’s still not working.
In fact neither the settings.json isn’t accessible so it has to be something else.
This is the first echo when I run “iron”, which looks ok.
meteor run --settings /Users/Vlad/Documents/dev-bay/studman-iron/config/development/settings.json


My env.sh looks like this now:

exports MAILGUN_API_URL = 'https://api.mailgun.net/xxxxxxxxxxxxx.org/messages'
exports MAILGUN_API_KEY = ‘key-xxxxxxxxxb'
exports MAILGUN_DOMAIN = 'sandboxxxxxxxxx.mailgun.org'
    

Vlad Blindu
vlad.blindu@gmail.com

**Comment by chrisbutler** [comment]
@vladblindu what does your `settings.json` file look like and how (and where) are you trying to access it?

**Comment by vladblindu** [comment]
I tried to put the same info in the settings.json file to use them on the server in the bootstrap.js file, where I’m configuring the login services and so forth.
After the last email I tried to see if the todos application in Chris classes has the same behaviour, and no “IT WORKS”.

The only difference between these two is that stud man-iron has a “-“ in the middle while todos doesn’t.
They are in the same folder "dev-bay”. 
The Studman-iron is here: https://github.com/vladblindu/studman-iron
If you think it helps, throw an eye.

this is the settings json:

{
  "public": {
  },

  "MAILGUN_API_URL": "https://api.mailgun.xxxxxxxxxxxxxxxxx.mailgun.org/messages",
  "MAILGUN_API_KEY": "key-6xxxxxxxxxxxxx",
  "MAILGUN_DOMAIN":"sandbox0xxxxxxxxxxxx8.mailgun.org",  
}
Vlad Blindu
vlad.blindu@gmail.com

**Comment by vladblindu** [comment]
By the way I checked Chris’s code in the classes video and it’s “export”. in env.sh.
It has to be something different.

Vlad Blindu
vlad.blindu@gmail.com

**Comment by chrisbutler** [comment]
he has it wrong. i'll make a PR to fix the generator, since my comment on the commit seems to have gone unnoticed: https://github.com/iron-meteor/iron-cli/commit/7d31b8dfda514eade9a2c6cd2077450bd64521e7#commitcomment-9849520

the reason it works in the video is because it's already in the database from the earlier example.

**Comment by chrisbutler** [comment]
if you change this line https://github.com/vladblindu/studman-iron/blob/master/app/server/bootstrap.js#L55 to `Meteor.settings.GOOGLE_API_ID` it should pull from the settings file

if you change it to `process.env.GOOGLE_API_ID` it should pull from the environment file

**Comment by vladblindu** [comment]
You are right. I’m a “part-time” coder, but from my node.js experience I recall this was thee syntax.
Vlad Blindu
vlad.blindu@gmail.com

**Comment by vladblindu** [comment]
BINGO!

But, it works with export, not exports. And probably this is because it’s shell  not node.js.
Tried both to be sure.

To tell you the truth I don’t understand why it didn’t work while I tried the process.env variant.
The important thing is that you helped me fix it. 

Thanks a lot for your time.

Vlad Blindu
vlad.blindu@gmail.com

**Comment by chrisbutler** [comment]
@vladblindu happy to help. when you tested, did you reset the app between changes? if not, your results would be affected by which order you tested them in

**Comment by vladblindu** [comment]
Probably I didn’t restart, or I had more typos than restarts.

So, the issue should be closed.
 For anybody making the same mistakes I did:

1. Restart the server after changing the env.sh file for the changes to take effect.
2. The data in the settings.json file should be accessed with Meteor.settings.MY_VAR.

Thanks again for your time.

Vlad Blindu
vlad.blindu@gmail.com

**Comment by cmather** [comment]
Hi @vladblindu, it looks like you summarized the findings nicely. To recap for others who might be having issues here:

1. You must restart the server after making changes to the env.sh file. Changes will not automatically be reflected. This is because only the meteor app files are watched for changes and that's built into the meteor tool itself, not iron.

2. You have a choice to use settings.json or environment variables for server side settings. If you're on windows, I don't think env.sh will even work (someone from windows can tell me the exact behavior though).

3. The reason I use `export VARIABLE_NAME="value"` instead of `VARIABLE_NAME="value"` is so that if the process forks a new process, the new process has access to the environment variables too. The `export` command makes sure the environment variable survives a fork. For more details check out this SO answer: http://stackoverflow.com/questions/13795237/what-does-the-export-command-do.

**Comment by chrisbutler** [comment]
@cmather i was basing my export vs exports comment on using node-env-file, but i see that we're not using it anymore (https://github.com/iron-meteor/iron-cli/blob/2bddcf8691559a6f21b4f7eba38354430c403b94/lib/commands/run.js)

**Comment by cmather** [comment]
yeah i pulled out the library for that reason. i'm not sure why it would work at all.
