### ISSUE TITLE
Change command name to "iron"

### ISSUE THREAD

**Issue by cmather** [iron-meteor/iron-cli#77]
Hey @scott-mcpherson! Hope you've been well.

What do you think about changing the command name to 'iron' instead of 'em'. I could make the change if you're good with it. A couple of thoughts/reasons:

1. I'd like to move the iron packages into their own github organization since we have multiple contributors and it's not just an EM thing.
2. The name 'iron' kind of makes more sense since the app is being organized around iron router.
3. We have an internal cli called 'em' for managing EM class projects so it's super confusing for us :-).

I think the easy way to do this is to keep all the internal lib stuff the same, and just change the command executable to 'iron'. Then we could migrate the other stuff slowly over time. Let me know what you think. I'm hoping to start recording some lessons on it today.

**Comment by scott-mcpherson** [comment]
Hey @cmather, I'm doing great. Hope all is well with you too.

I like the idea of changing the command from em to iron. I agree, it makes sense to keep the naming consistent and everything iron related under the same organization. 

And that migration strategy sounds good too. 

I was actually getting ready to merge a branch that I've been working on in the next week or so. It adds a new flag option that sets up a project similar to the one that's being setup now with the init/create command, except it adds a couple of extra files and packages that enables the developer to rapidly build responsive mobile/web apps. 

It leverages foundation for apps for the styling, but because foundation for apps is so reliant on angular, I've had to rewrite some of the stuff from scratch. Plus there's some extras, for example, split views on desktop that automatically turn into animated table views on mobile devices with a simple spacebars helper.

It's not quite ready yet, but if you want I could push the branch for you to check out, or I could wait until you begin migrating everything over and we could figure out how to work it in from there. 

What do you think?

**Comment by cmather** [comment]
Hey @scott-mcpherson, Cool. I'm making changes in the cmather branch now. I'll push it up once in a little while. Hopefully it doesn't conflict too much with your work. 

Changes include:

1. Auto install iron router
2. Biggest change is changing the directory structure to:
```bash
my-project/
  app/
    .meteor
    other app directories
  config/
  bin/
  .iron
    config.json
```
I've also changed the command to 'iron'. Once I get the generators working again with the new dir structure the outstanding todos will be to:

1. upgrade command to upgrade a project on to the new structure
2. proxy unknown iron commands to meteor inside the `app` directory so it's easy to run meteor commands from the project folder
3. create new npm package called iron-meteor
4. move project to iron-meteor/iron-cli

**Comment by cmather** [comment]
Btw the reason for putting the meteor app into its own directory is so that we can have bin scripts and config files that don't take part in the meteor bundle process. It will probably also be helpful for putting tests at some point.

**Comment by scott-mcpherson** [comment]
Sounds good @cmather. I like the idea of moving the bin/config stuff out of the project's root.
